---
- hosts: localhost
  tasks:
    - name: Display local HOME environment variable
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.env', 'HOME') }} is the local HOME environment variable"
