---
- hosts: test_servers
  tasks:
    - name: Create directory
      ansible.builtin.file:
        path: /home/ansible/tmp
        state: directory
        owner: youn410
        mode: "0755"

    - name: Copy file
      ansible.builtin.copy:
        src: /etc/hosts
        dest: /home/ansible/tmp/hosts
        owner: youn410
        mode: "0644"
