---
- name: configure / Add Node Exporter port
  ansible.posix.firewalld:
    port: "{{ nodeexporter_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true

- name: configure / Add Node Exporter group
  ansible.builtin.group:
    name: "{{ nodeexporter_os_group }}"
    state: present

- name: configure / Add Node Exporter user
  ansible.builtin.user:
    name: "{{ nodeexporter_os_user }}"
    groups: "{{ nodeexporter_os_group }}"
