---
- name: configure / Update prometheus.yml
  ansible.builtin.template:
    src: templates/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: "{{ nodeexporter_os_user }}"
    group: "{{ nodeexporter_os_group }}"
    mode: '0755'

- name: configure / Reload and Enable node_exporter service
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: true
    daemon_reload: true
