---
- name: Initialize OS setting for Linux Servers
  hosts: linux_servers
  become: true

  tasks:
    - ansible.builtin.import_role: name=common/hostname
      tags: hostname
    - ansible.builtin.import_role: name=common/locale
      tags: locale
    - ansible.builtin.import_role: name=common/packages
      tags: packages
