---
- name: download / Download Prometheus file
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    dest: /usr/local/src
    owner: "{{ prometheus_os_user }}"
    group: "{{ prometheus_os_group }}"
    remote_src: true

- name: configure / Make directory /var/lib/prometheus
  ansible.builtin.file:
    path: /var/lib/prometheus
    state: directory
    owner: "{{ prometheus_os_user }}"
    group: "{{ prometheus_os_group }}"
    mode: '0755'

- name: configure / Create prometheus symbolic link
  ansible.builtin.file:
    src: /usr/local/src/prometheus-{{ prometheus_version }}.linux-amd64/prometheus
    dest: /usr/local/prometheus
    state: link
